insert into category values(1,"colors");
insert into category values(2,"Erasers");
insert into category values(3,"pencils");
insert into category values(4,"pens");
insert into category values(5,"papers");
insert into category values(6,"sharpners");
insert into category values(7,"Exam pads");
insert into category values(8,"Pencil Box");
insert into category values(9,"Calculators");
insert into category values(10,"Notebooks");
insert into category values(11,"Files");
insert into category values(12,"Folders");
insert into category values(13,"Tools");
insert into category values(14,"scissors");
insert into category values(15,"glue");
insert into category values(16,"Staplers");
insert into category values(17,"Punching machine");
insert into category values(18,"Printing Suplies");
insert into category values(19,"School Supplies");
insert into category values(20,"Boards & Dusters");

